#!/usr/bin/env python3
"""Generate the embedded data bundles the web app ships with.

Reads the validated Phase-1 CSVs in data/ and emits two files that carry the
SAME numbers so the page and the chat evaluator never disagree:

  app/public/data.js       -> window.YB_DATA = {...}   (front-end rendering)
  app/api/_budget-data.js  -> export const BUDGET={...} (chat system prompt)

Run from the repo root:  python3 build_data.py
"""
import csv
import json
import os

DATA = "data"
OUT_PUBLIC = "app/public/data.js"
OUT_API = "app/api/_budget-data.js"

# FY27 tax mechanics (from the draft "Citizens" book — see FINDINGS.md).
TAX_BASE_FY27 = 3_221_025_900
HOME = 500_000
YEARS = [2024, 2025, 2026, 2027]


def load(name):
    with open(os.path.join(DATA, name), newline="") as fh:
        return list(csv.DictReader(fh))


def num(x):
    if x in ("", None):
        return 0.0
    return float(x)


def build():
    # ---- headline summary metrics (summary_long.csv is metric/year/amount) ----
    summ = {}
    for r in load("summary_long.csv"):
        summ.setdefault(r["metric"], {})[int(r["fiscal_year"])] = num(r["amount"])

    def series(metric):
        return {str(y): summ.get(metric, {}).get(y) for y in YEARS}

    summary = {
        "years": YEARS,
        "education": series("education_appropriation"),
        "municipal": series("municipal_appropriation"),
        "county": series("county_tax"),
        "totalGF": series("total_gf_expenses"),
        "netLevy": series("net_gf_property_tax"),
        "taxBase": series("gf_net_tax_base"),
        "rate": series("tax_rate_per_1000"),
    }

    # ---- municipal categories (wide) ----
    categories = []
    for r in load("master_by_category.csv"):
        categories.append({
            "name": r["category"],
            "fy24": num(r["budget_2024"]),
            "fy27": num(r["budget_2027"]),
        })
    categories.sort(key=lambda c: -c["fy27"])

    # ---- school functions (fy27_budget) ----
    school = []
    for r in load("school_functions.csv"):
        school.append({
            "name": r["function"].strip(),
            "fy27": num(r["fy27_budget"]),
        })
    school.sort(key=lambda s: -s["fy27"])

    # ---- scenarios (enriched with side / target / impact for the UI) ----
    def classify_target(group, scen):
        s = scen.lower()
        if group == "Revenue":
            return "revenue"
        if group == "Compensation":
            return "both"          # town + school payrolls
        if "school" in s or "athletic" in s:
            return "schools"
        return "municipal"

    def impact_tier(home):
        h = abs(home)
        if h >= 100:
            return "high"
        if h >= 30:
            return "moderate"
        return "small"

    scenarios = []
    for r in load("scenarios.csv"):
        home = int(num(r["home_500k_impact"]))
        typ = r["type"]
        scenarios.append({
            "group": r["group"],
            "scenario": r["scenario"],
            "annual": int(num(r["annual_dollars"])),
            "type": typ,
            "side": "revenue" if typ == "revenue" else "cut",
            "target": classify_target(r["group"], r["scenario"]),
            "impact": impact_tier(home),
            "feasibility": r["feasibility"],
            "rate": float(r["rate_impact"]),
            "home": home,
            "note": r["note"],
        })

    # ---- mechanics / conversion factor ----
    rate_per_million = 1_000_000 * 1000 / TAX_BASE_FY27          # ~0.3105
    home_per_million = 1_000_000 * HOME / TAX_BASE_FY27          # ~155.2
    home_bill_fy27 = summary["rate"]["2027"] * HOME / 1000        # 7625

    mechanics = {
        "taxBaseFY27": TAX_BASE_FY27,
        "home": HOME,
        "rateFY27": summary["rate"]["2027"],
        "homeBillFY27": round(home_bill_fy27),
        "ratePerMillion": round(rate_per_million, 3),
        "homePerMillion": round(home_per_million),
    }

    return {
        "meta": {
            "generated": "phase-1 dataset",
            "fyNote": "FY27 figures are from the 04.09 DRAFT 'Citizens' budget book.",
        },
        "summary": summary,
        "categories": categories,
        "school": school,
        "scenarios": scenarios,
        "mechanics": mechanics,
    }


def main():
    bundle = build()
    payload = json.dumps(bundle, indent=2)

    os.makedirs(os.path.dirname(OUT_PUBLIC), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_API), exist_ok=True)

    header = "// AUTO-GENERATED by build_data.py — do not edit by hand.\n"
    with open(OUT_PUBLIC, "w") as fh:
        fh.write(header)
        fh.write("window.YB_DATA = " + payload + ";\n")
    with open(OUT_API, "w") as fh:
        fh.write(header)
        fh.write("export const BUDGET = " + payload + ";\n")

    ed = bundle["summary"]["education"]["2027"]
    mu = bundle["summary"]["municipal"]["2027"]
    co = bundle["summary"]["county"]["2027"]
    tot = bundle["summary"]["totalGF"]["2027"]
    print(f"Wrote {OUT_PUBLIC} and {OUT_API}")
    print(f"FY27 GF ${tot:,.0f}  = edu ${ed:,.0f} ({ed/tot:.1%}) + "
          f"muni ${mu:,.0f} ({mu/tot:.1%}) + county ${co:,.0f} ({co/tot:.1%})")
    print(f"{len(bundle['scenarios'])} scenarios, {len(bundle['school'])} school functions, "
          f"{len(bundle['categories'])} muni categories")
    print(f"Conversion: $1M cut -> -${bundle['mechanics']['ratePerMillion']} rate -> "
          f"-${bundle['mechanics']['homePerMillion']}/home")


if __name__ == "__main__":
    main()
