// AUTO-GENERATED by build_data.py — do not edit by hand.
export const BUDGET = {
  "meta": {
    "generated": "phase-1 dataset",
    "fyNote": "FY27 figures are from the 04.09 DRAFT 'Citizens' budget book."
  },
  "summary": {
    "years": [
      2024,
      2025,
      2026,
      2027
    ],
    "education": {
      "2024": 36590456.0,
      "2025": 39278131.0,
      "2026": 42248050.0,
      "2027": 44111921.0
    },
    "municipal": {
      "2024": 16742702.0,
      "2025": 17968197.0,
      "2026": 18797126.0,
      "2027": 19561023.0
    },
    "county": {
      "2024": 1525119.0,
      "2025": 1593135.0,
      "2026": 1680359.0,
      "2027": 1904994.0
    },
    "totalGF": {
      "2024": 54858277.0,
      "2025": 58839463.0,
      "2026": 62725535.0,
      "2027": 65577938.0
    },
    "netLevy": {
      "2024": 39299961.0,
      "2025": 42980458.0,
      "2026": 46213215.0,
      "2027": 48761761.0
    },
    "taxBase": {
      "2024": 1676323360.0,
      "2025": 1682138280.0,
      "2026": 3211136100.0,
      "2027": 3221025900.0
    },
    "rate": {
      "2024": 23.54,
      "2025": 25.67,
      "2026": 14.55,
      "2027": 15.25
    }
  },
  "categories": [
    {
      "name": "General Government",
      "fy24": 4047869.0,
      "fy27": 4954551.0
    },
    {
      "name": "Public Safety",
      "fy24": 3780688.0,
      "fy27": 4525442.0
    },
    {
      "name": "Public Works",
      "fy24": 3616539.0,
      "fy27": 4101724.0
    },
    {
      "name": "Capital Programs",
      "fy24": 3320049.0,
      "fy27": 3392947.0
    },
    {
      "name": "Public Services",
      "fy24": 2006458.0,
      "fy27": 2480603.0
    },
    {
      "name": "Health & Welfare",
      "fy24": 180440.0,
      "fy27": 105758.0
    }
  ],
  "school": [
    {
      "name": "Regular Program",
      "fy27": 19763703.5
    },
    {
      "name": "Special Ed Programs",
      "fy27": 7433166.07
    },
    {
      "name": "Operations and Mainten",
      "fy27": 3557043.94
    },
    {
      "name": "Debt Service",
      "fy27": 2451132.0
    },
    {
      "name": "Office of the Principa",
      "fy27": 1923956.23
    },
    {
      "name": "Student Transportation",
      "fy27": 1821169.9
    },
    {
      "name": "Technology - Instructi",
      "fy27": 1438104.09
    },
    {
      "name": "Extra Curr Athletics",
      "fy27": 1107525.37
    },
    {
      "name": "Superintendent School",
      "fy27": 1065602.17
    },
    {
      "name": "Guidance",
      "fy27": 1035421.9
    },
    {
      "name": "Library",
      "fy27": 578211.7
    },
    {
      "name": "Student Health",
      "fy27": 525018.75
    },
    {
      "name": "Improvement of Instruc",
      "fy27": 435083.92
    },
    {
      "name": "English Language Learn",
      "fy27": 412587.9
    },
    {
      "name": "Extra and Co Curr Acti",
      "fy27": 296262.59
    },
    {
      "name": "Capital Reserves",
      "fy27": 102231.0
    },
    {
      "name": "Contingency",
      "fy27": 85000.0
    },
    {
      "name": "School Nutrition Trans",
      "fy27": 65000.0
    },
    {
      "name": "Assessment",
      "fy27": 11700.0
    },
    {
      "name": "Student Support 504",
      "fy27": 4000.0
    }
  ],
  "scenarios": [
    {
      "group": "Muni \u00b7 Climate/Conservation",
      "scenario": "Eliminate Sustainability Coordinator (position)",
      "annual": 95465,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.03,
      "home": 15,
      "note": "Cuts a staff position; ends in-house climate/energy work"
    },
    {
      "group": "Muni \u00b7 Climate/Conservation",
      "scenario": "Cut Conservation Land Maintenance",
      "annual": 28000,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.009,
      "home": 4,
      "note": "Defer/volunteer-shift trail & open-space upkeep"
    },
    {
      "group": "Muni \u00b7 Climate/Conservation",
      "scenario": "Cut Shellfish Conservation",
      "annual": 7000,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.002,
      "home": 1,
      "note": "Clam-flat mgmt; may have state license-revenue tie"
    },
    {
      "group": "Muni \u00b7 Climate/Conservation",
      "scenario": "End RRCT (Royal River Conservation Trust) subsidy",
      "annual": 4500,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.001,
      "home": 1,
      "note": "Discretionary partner contribution"
    },
    {
      "group": "Muni \u00b7 Climate/Conservation",
      "scenario": "Cut Tree Care / urban forestry",
      "annual": 74000,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.023,
      "home": 11,
      "note": "Liability + canopy/property-value risk; deferral safer than elimination"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "Eliminate STAY Program reserve",
      "annual": 238000,
      "type": "cut",
      "feasibility": "VERIFY / self-defeating?",
      "rate": 0.074,
      "home": 37,
      "note": "Appears to be senior tax-relief/aging support \u2014 cutting it hurts the residents most squeezed by property tax. Confirm purpose before listing"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "Cut Aging In Place program",
      "annual": 41000,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.013,
      "home": 6,
      "note": "Senior services"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "Eliminate Community Behavioral Health Liaison (position)",
      "annual": 41393,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.013,
      "home": 6,
      "note": "New social-services position"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "End Metro regional transit subsidy",
      "annual": 131547,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.041,
      "home": 20,
      "note": "Regional bus service; equity/access + possible regional-compact obligation"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "End Historical Society appropriation",
      "annual": 27000,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.008,
      "home": 4,
      "note": "Discretionary grant"
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "Zero out Human Service Agencies (1410)",
      "annual": 4850,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.002,
      "home": 1,
      "note": "Opportunity Alliance, Family Crisis Center, Area Agency on Aging, etc."
    },
    {
      "group": "Muni \u00b7 Senior/Social",
      "scenario": "Cut GPCOG / regional planning dues",
      "annual": 20228,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.006,
      "home": 3,
      "note": "Regional planning council membership"
    },
    {
      "group": "Muni \u00b7 Capital defer",
      "scenario": "Defer Parks & Playgrounds reserve",
      "annual": 215000,
      "type": "one-time",
      "feasibility": "town-controlled",
      "rate": 0.067,
      "home": 33,
      "note": "One-year deferral"
    },
    {
      "group": "Muni \u00b7 Capital defer",
      "scenario": "Defer Library Building reserve",
      "annual": 30000,
      "type": "one-time",
      "feasibility": "town-controlled",
      "rate": 0.009,
      "home": 5,
      "note": "One-year deferral"
    },
    {
      "group": "Muni \u00b7 Capital defer",
      "scenario": "Cut municipal CAPITAL RESERVES contribution 50%",
      "annual": 909360,
      "type": "one-time",
      "feasibility": "town-controlled",
      "rate": 0.282,
      "home": 141,
      "note": "Broad one-year deferral of capital set-asides"
    },
    {
      "group": "Muni \u00b7 Broad",
      "scenario": "Eliminate the Community Services dept (1570) entirely",
      "annual": 385964,
      "type": "cut",
      "feasibility": "aggressive",
      "rate": 0.12,
      "home": 60,
      "note": "Wipes climate+senior+regional+historical+shellfish at once"
    },
    {
      "group": "Muni \u00b7 Broad",
      "scenario": "5% across-the-board cut to municipal OPERATING (excl debt/capital)",
      "annual": 808404,
      "type": "cut",
      "feasibility": "town-controlled",
      "rate": 0.251,
      "home": 125,
      "note": "Operating = municipal minus debt & capital"
    },
    {
      "group": "Amenities (named)",
      "scenario": "Town library \u2014 hours/consolidate (not eliminate)",
      "annual": 369216,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.115,
      "home": 57,
      "note": "Full elimination forfeits MaineCat/ILL + property value"
    },
    {
      "group": "Amenities (named)",
      "scenario": "Parks & Rec \u2014 reduced maintenance / Friends model",
      "annual": 378732,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.118,
      "home": 59,
      "note": "Deed restrictions (LWCF) bar full closure of some parks"
    },
    {
      "group": "Amenities (named)",
      "scenario": "School athletics \u2014 pay-to-play (realistic recovery)",
      "annual": 719891,
      "type": "cut",
      "feasibility": "caution",
      "rate": 0.223,
      "home": 112,
      "note": "Title IX + fee waivers cap recovery ~65%"
    },
    {
      "group": "Amenities (named)",
      "scenario": "School transportation \u2014 route optimization (not elimination)",
      "annual": 455292,
      "type": "cut",
      "feasibility": "constrained",
      "rate": 0.141,
      "home": 71,
      "note": "SpEd/walk-zone mandates + EPS state-aid clawback limit net savings"
    },
    {
      "group": "Compensation",
      "scenario": "0% COLA vs 3% step, town+school (1 yr, negotiated)",
      "annual": 1068000,
      "type": "cut",
      "feasibility": "bargained",
      "rate": 0.332,
      "home": 166,
      "note": "~$356k per 1% across both payrolls; no service loss"
    },
    {
      "group": "Revenue",
      "scenario": "Waterfront recapture (mooring/commercial fees + reassessment + excise audit)",
      "annual": 450000,
      "type": "revenue",
      "feasibility": "study needed",
      "rate": 0.14,
      "home": 70,
      "note": "Mid of $300-600k range; boats themselves are excise-capped"
    },
    {
      "group": "Revenue",
      "scenario": "NYA non-exempt-use audit + service charges / PILOT",
      "annual": 250000,
      "type": "revenue",
      "feasibility": "negotiated/legal",
      "rate": 0.078,
      "home": 39,
      "note": "Mid of $100-400k; cannot force exemption removal"
    },
    {
      "group": "Revenue",
      "scenario": "Fee/cost-recovery (rescue billing + STR fees + stormwater utility)",
      "annual": 400000,
      "type": "revenue",
      "feasibility": "town-controlled",
      "rate": 0.124,
      "home": 62,
      "note": "Mid of $250-650k range"
    }
  ],
  "mechanics": {
    "taxBaseFY27": 3221025900,
    "home": 500000,
    "rateFY27": 15.25,
    "homeBillFY27": 7625,
    "ratePerMillion": 0.31,
    "homePerMillion": 155
  }
};
